### ISSUE TITLE
validate_password_length support

### ISSUE THREAD

**Issue by pymhd** [lean-delivery/ansible-role-mysql#11]
When i am trying to use validate_password_length additional_parameter for my.cnf file i get error on task "Start MySQL service"
In mysqld service i see this messages:
[ERROR] --initialize specified but the data directory has files in it. Aborting.
[ERROR] Aborting

So i made some kind of workaround to add this parameter in post install tasks but it is really inconvenient. Maybe you could add this as separate variable out of additional_parameters scope to get role working with possibility to set simple passwords 

Playbook example: 
```
- role: '../roles/lean_delivery.mysql'
    mysql_username: "mysql"
    mysql_groupname: "mysql"
    mysql_version: 5.7
    mysql_root_password: "*********************"
    additional_parameters:
      - name: validate_password_length
        value: 4
    tags:
      - mysql
```
