### ISSUE TITLE
Add support ansible 2.9

### ISSUE THREAD

**Issue by pavelpikta** [lean-delivery/ansible-role-mysql#14]
##### SUMMARY

Add supprot ansible 2.9.*
##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
2.9.*
```

##### OS / ENVIRONMENT

Centos 7
##### STEPS TO REPRODUCE

```yaml
---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-mysql
      mysql_root_password: 88TEM-veDRE<888serd
      mysql_databases:
        - name: example2_db
          encoding: latin1
          collation: latin1_general_ci
      mysql_users:
        - name: example2_user
          host: "%"
          password: Sime32-SRRR-password
          priv: "example2_db.*:ALL"
      mysql_port: 3306
      mysql_bind_address: '0.0.0.0'
      mysql_daemon: mysqld
      mysql_version: 5.7
```

##### EXPECTED RESULTS

Role complete successfully
##### ACTUAL RESULTS

```
369     TASK [ansible-role-mysql : Update mysql root password for all root accounts] ***
370     fatal: [test-docker-centos7-mysql]: FAILED! => changed=false 
371       msg: 'unable to connect to database: (1045, "Access denied for user ''root''@''localhost'' (using password: NO)")'
372     
373     TASK [ansible-role-mysql : Create databases and users] *************************
374     included: /builds/lean-delivery/ansible-role-mysql/tasks/databases_and_users.yml for test-docker-ubuntu1804-mysql
375     
376     TASK [ansible-role-mysql : Ensure MySQL databases are present] *****************
377     changed: [test-docker-ubuntu1804-mysql] => (item={'name': 'example2_db', 'encoding': 'latin1', 'collation': 'latin1_general_ci'})
378     
379     TASK [ansible-role-mysql : Ensure MySQL users are present] *********************
380     changed: [test-docker-ubuntu1804-mysql] => (item=None)
381     changed: [test-docker-ubuntu1804-mysql]
382     
383     RUNNING HANDLER [ansible-role-mysql : restart mysql] ***************************
384     included: /builds/lean-delivery/ansible-role-mysql/tasks/mysql_restart.yml for test-docker-ubuntu1804-mysql
385     
386     RUNNING HANDLER [ansible-role-mysql : Stop mysql] ******************************
387     changed: [test-docker-ubuntu1804-mysql]
388     
389     RUNNING HANDLER [ansible-role-mysql : Wait until the lock file is removed] *****
390     ok: [test-docker-ubuntu1804-mysql]
391     
392     RUNNING HANDLER [ansible-role-mysql : Start mysql] *****************************
393     changed: [test-docker-ubuntu1804-mysql]
394     
395     RUNNING HANDLER [ansible-role-mysql : Wait for service to be ready] ************
396     ok: [test-docker-ubuntu1804-mysql]
397     
398     PLAY RECAP *********************************************************************
399     test-docker-centos7-mysql  : ok=39   changed=18   unreachable=0    failed=2    skipped=5    rescued=0    ignored=0
400     test-docker-ubuntu1804-mysql : ok=33   changed=13   unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
```
