### ISSUE TITLE
Unable to install not latest 5.7 version

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [lean-delivery/ansible-role-mysql#22]
##### SUMMARY
Unable to install not latest 5.7.31 version (latest is 5.7.33).

##### ISSUE TYPE
 - Bug Report

##### OS / ENVIRONMENT
Ubuntu 16

##### STEPS TO REPRODUCE
```yaml
    - role: lean_delivery.mysql
      mysql_version: 5.7
      mysql_packages:
        - mysql-server=5.7.31-1ubuntu16.04
```

##### WORKAROUND
Run pre-task
```yaml
    - name: Install mysql apt repo
      apt:
        deb: "{{ item }}"
      loop:
        - https://downloads.mysql.com/archives/get/p/23/file/mysql-community-client_5.7.31-1ubuntu16.04_amd64.deb
        - https://downloads.mysql.com/archives/get/p/23/file/mysql-client_5.7.31-1ubuntu16.04_amd64.deb
        - https://downloads.mysql.com/archives/get/p/23/file/mysql-community-server_5.7.31-1ubuntu16.04_amd64.deb
        - https://downloads.mysql.com/archives/get/p/23/file/mysql-server_5.7.31-1ubuntu16.04_amd64.deb
      become: true
```
