### ISSUE TITLE
Support for plugin config in "additional_parameters"

### ISSUE THREAD

**Issue by colinleefish** [lean-delivery/ansible-role-mysql#9]
##### SUMMARY

Currently everything under "additional_parameters" section will be added to /etc/my.cnf as parameters *before database initialization*. However, if we add plugin-specific parameters (e.g. "validate_password_policy", the initialization process will fail.

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = None
  configured module search path = ['/Users/colinleefish/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/colinleefish/.pyenv/versions/3.6.8/envs/ansible_py3/lib/python3.6/site-packages/ansible
  executable location = /Users/colinleefish/.pyenv/versions/ansible_py3/bin/ansible
  python version = 3.6.8 (default, Apr  5 2019, 16:44:44) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

`HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False`

##### OS / ENVIRONMENT

- CentOS 7.6
- MySQL 5.7
##### STEPS TO REPRODUCE

```yaml
---
- hosts: mysql
  roles:
  - role: lean_delivery.mysql
    mysql_daemon: "mysqld"
    mysql_version: "5.7"
    mysql_root_password: "a_stupid_password"
    additional_parameters:
    - name: character-set-server
      value: "utf8mb4"
    - name: collation-server
      value: "utf8mb4_unicode_ci"
    - name: validate_password_policy
      value: "LOW"
```

##### EXPECTED RESULTS

MySQL up and running

##### ACTUAL RESULTS

```
`fatal: [172.28.128.9]: FAILED! => {"changed": false, "msg": "Unable to start service mysqld: Job for mysqld.service failed because the control process exited with error code. See \"systemctl status mysqld.service\" and \"journalctl -xe\" for details.\n"}`
```
